### ISSUE TITLE
Consider renaming crate

### ISSUE THREAD

**Issue by Noah2610** [tversteeg/ld46#1]
```
cargo install ld46
```
is cool, but I think it would be better if the crate's name contains "Fermi Paradox".
Maybe `ld46-fermi-paradox`?

**Comment by tversteeg** [comment]
I'm okay with this, but is that possible on crates.io? I couldn't find any way to rename a published crate..

**Comment by Noah2610** [comment]
I don't think it is possible to delete/rename a crate on crates.io, but I think it's still better to re-publish it with a name like `ld46-fermi-paradox`, instead of just `ld46`.
You could yank it from crates.io, but I don't think it really matters.

**Comment by tversteeg** [comment]
Isn't that worse in this case though? Because that means there will be 2 crates.

**Comment by Noah2610** [comment]
However you like, I thought if the crate is up on crates.io, it should include the name.
But if you don't really need it up, then don't worry about it!
It's your call, no worries either way :)

**Comment by tversteeg** [comment]
I do agree though, I just don't like having 2 crates doing the same thing. Too bad I can't yank a crate.

Thanks for the suggestion!

**Comment by Noah2610** [comment]
I totally get that, no problem!
